import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:intl/intl.dart';
import '../../features/expenses/domain/expense_model.dart';

class PdfHelper {
  static Future<void> generateAndPrint(List<ExpenseModel> expenses, String walletName) async {

    // 1. Load "Tiro Bangla" (Best for complex Bengali scripts)
    final ttf = await PdfGoogleFonts.tiroBanglaRegular();

    final doc = pw.Document();

    final total = expenses.fold(0.0, (sum, item) => sum + item.amount);

    doc.addPage(
      pw.MultiPage(
        // 2. Apply the Font to BOTH Base and Bold
        // This prevents the font from breaking when text is bold (like headers)
        theme: pw.ThemeData.withFont(
          base: ttf,
          bold: ttf,
        ),
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return [
            // Header
            pw.Header(
              level: 0,
              child: pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Text('Monthly Expense Report', style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold)),
                  pw.Text(walletName, style: const pw.TextStyle(fontSize: 18, color: PdfColors.grey700)),
                ],
              ),
            ),
            pw.SizedBox(height: 20),

            // Summary
            pw.Container(
              alignment: pw.Alignment.centerRight,
              child: pw.Text(
                'Total Spent: ৳${total.toStringAsFixed(0)}',
                style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold, color: PdfColors.teal),
              ),
            ),
            pw.SizedBox(height: 20),

            // Table
            pw.Table.fromTextArray(
              context: context,
              border: pw.TableBorder.all(color: PdfColors.grey300),
              headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, color: PdfColors.white),
              headerDecoration: const pw.BoxDecoration(color: PdfColors.teal),
              cellAlignment: pw.Alignment.centerLeft,
              data: <List<String>>[
                <String>['Date', 'Item', 'Category', 'Amount'],
                ...expenses.map((e) => [
                  DateFormat('yyyy-MM-dd').format(e.date),
                  e.title,
                  e.category,
                  '৳${e.amount}',
                ]),
              ],
            ),

            pw.Padding(padding: const pw.EdgeInsets.all(10)),
            pw.Text(
                "Generated by Monthly Expense App",
                style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey500)
            ),
          ];
        },
      ),
    );

    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => doc.save(),
    );
  }
}